title: PPx Customize Articles
author: tar80
email: tar80master@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Copyright 2021 tar80
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
github_username: tar80

## RSS feed settings
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

## page settings
# page_excerpts: true
paginate: 12
paginate_path: "/pages/:num"
highlighter: rouge
highlighter-theme: pca
default:
  scope:
    path: "public/img"
  values:
    image: true
svg:
  optimize: true

## Build settings
# theme: minima
category_dir: category/
# tag_dir: tag/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Exclude from processing.
## The following items will not be processed, by default.
## Any item listed under the `exclude:` key here will be automatically added to
## the internal "default list".
##
## Excluded items can be processed by explicitly listing the directories or
## their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
